# @package _global_

defaults:
  - base_env

# Env structure
env:
  _target_: protomotions.envs.box.env.PushBox
  config:
    enable_height_termination: True
    steering_params:
      heading_change_steps_min: 40
      heading_change_steps_max: 150
      random_heading_probability: 0.2
      standard_heading_change: 1.57
      tar_speed_min: 1.2
      tar_speed_max: 6
      standard_speed_change: 0.3
      stop_probability: 0.05
      obs_size: 3

    box_params:
      goal_dist_thresh: 0.5 # 0.5米内算到达
      contact_reward: 2.0
      goal_reward: 10.0
      obs_size: 6
    
    scene_lib:
      _target_: protomotions.utils.scene_lib.SceneLib # 指定 SceneLib 类
      # 定义一个场景列表，这里我们只有一个场景
      scenes:
        - _target_: protomotions.utils.scene_lib.Scene # 指定 Scene 类
          # 这个场景里包含的物体列表
          objects:
            # 定义我们的箱子
            - _target_: protomotions.utils.scene_lib.SceneObject
              name: "box" # 【重要】这个名字必须和 PushBoxEnv 里 get_object_by_name 使用的名字一致
              # 使用内置的几何体，而不是从文件加载
              object_type: "cuboid" 
              # 物体的物理和视觉选项
              options:
                _target_: protomotions.utils.scene_lib.ObjectOptions
                size: [0.4, 0.4, 0.4]
                mass: 2.0
                friction: 0.8
                fix_base_link: False # 必须为 False，否则箱子不能动
              # 初始位姿可以设为0，因为 env._reset_box_and_goal 会立即重置它
              translation: [0.0, 0.0, 0.0] 
              rotation: [0.0, 0.0, 0.0, 1.0]

# Globally accessible parameters
